version: "3.9"

services:
  zookeeper:
    image: zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:2181"
    volumes:
      - ./zookeeper-data:/data
      - ./zookeeper-datalog:/datalog

  kafka:
    image: confluentinc/cp-kafka
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:${ZOOKEEPER_PORT}"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: SSL://0.0.0.0:9093,BROKER://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: SSL://${SERVER_IP}:${KAFKA_PORT},BROKER://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SSL:SSL,BROKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker.keystore.pkcs12
      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker_creds
      KAFKA_SSL_KEY_CREDENTIALS: broker_creds
      #KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.kafka-1.truststore.pkcs12
      #KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka-1_truststore_creds
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "HTTPS"
      #KAFKA_SSL_CLIENT_AUTH: "required"
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms256M"

    ports:
      - "${KAFKA_PORT}:9093"
    volumes:
      - ./kafka-data:/var/lib/kafka/data
      - ./creds:/etc/kafka/secrets
    depends_on:
      - zookeeper
