version: "3.9"

services:
  zookeeper:
    image: zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:2181"
    volumes:
      - ./zookeeper-data:/data
      - ./zookeeper-datalog:/datalog

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:${ZOOKEEPER_PORT}"
      KAFKA_LISTENERS: "SSL://localhost:9092"
      KAFKA_ADVERTISED_LISTENERS: "SSL://${SERVER_IP}:${KAFKA_PORT}"
      KAFKA_INTER_BROKER_LISTENER_NAME: SSL
      KAFKA_SSL_KEYSTORE_LOCATION: '/etc/kafka/secrets/kafka.server.keystore.jks'
      KAFKA_SSL_KEYSTORE_PASSWORD: ${STOREPASS}
      KAFKA_SSL_KEY_CREDENTIALS: ${STOREPASS}
      KAFKA_SSL_TRUSTSTORE_LOCATION: '/etc/kafka/secrets/kafka.server.truststore.jks'
      KAFKA_SSL_TRUSTSTORE_PASSWORD: ${STOREPASS}
      KAFKA_SSL_CLIENT_AUTH: none
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms256M"
    ports:
      - "${KAFKA_PORT}:9092"
    volumes:
      - ./kafka-data:/var/lib/kafka/data
      - ./creds:/etc/kafka/secrets
    depends_on:
      - zookeeper
