version: "3.9"

services:
  zookeeper:
    image: zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:2181"
    volumes:
      - ./zookeeper-data:/data
      - ./zookeeper-datalog:/datalog

  kafka:
    image: confluentinc/cp-kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:${ZOOKEEPER_PORT}"
      KAFKA_LISTENERS: "SSL://localhost:9092"
      KAFKA_ADVERTISED_LISTENERS: "SSL://${SERVER_IP}:${KAFKA_PORT}"
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: store_creds
      KAFKA_SSL_KEY_CREDENTIALS: store_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: store_creds
      KAFKA_SSL_CLIENT_AUTH: none
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms256M"
    ports:
      - "${KAFKA_PORT}:9092"
    volumes:
      - ./kafka-data:/var/lib/kafka/data
      - ./creds:/etc/kafka/secrets
    depends_on:
      - zookeeper
