version: "3.9"

services:
  zookeeper:
    image: zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:2181"

  kafka:
    image: confluentinc/cp-kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:${ZOOKEEPER_PORT}"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://${SERVER_IP}:${KAFKA_PORT}"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms256M"
    ports:
      - "${KAFKA_PORT}:9092"
    depends_on:
      - zookeeper
