version: "3.9"

services:
  zookeeper:
    image: zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:2181"
    volumes:
      - ./zookeeper-data:/data
      - ./zookeeper-datalog:/datalog

  kafka:
    image: confluentinc/cp-kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:${ZOOKEEPER_PORT}"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "SASL_PLAINTEXT:SASL_PLAINTEXT"
      KAFKA_LISTENER_NAME_SASL_PLAINTEXT_SECURITY_PROTOCOL: "SASL_PLAINTEXT"
      KAFKA_LISTENER_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "SCRAM-SHA-256"
      KAFKA_LISTENER_SASL_MECHANISM: "SCRAM-SHA-256"
      KAFKA_SASL_ENABLED_MECHANISMS: "SCRAM-SHA-256"
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "SCRAM-SHA-256"
      KAFKA_LISTENERS: "SASL_PLAINTEXT://${SERVER_IP}:${KAFKA_PORT}"
      KAFKA_LISTENER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"myuser\" password=\"mypassword\";"
      KAFKA_ADVERTISED_LISTENERS: "SASL_PLAINTEXT://${SERVER_IP}:${KAFKA_PORT}"
      KAFKA_LISTENER_SECURITY_PROTOCOL: "SASL_PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms256M"
      KAFKA_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"myuser\" password=\"mypassword\";"
    ports:
      - "${KAFKA_PORT}:9092"
    volumes:
      - ./kafka-data:/var/lib/kafka/data
    depends_on:
      - zookeeper
